//
//  PostCommentReplayInteractor.swift
//  golos-ios
//
//  Created by msm72 on 11.06.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Business Logic protocols
protocol PostCommentReplayBusinessLogic {
    func doSomething(withRequestModel requestModel: PostCommentReplayModels.Something.RequestModel)
}

protocol PostCommentReplayDataStore {
//     var name: String { get set }
}

class PostCommentReplayInteractor: PostCommentReplayBusinessLogic, PostCommentReplayDataStore {
    // MARK: - Properties
    var presenter: PostCommentReplayPresentationLogic?
    var worker: PostCommentReplayWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: PostCommentReplayModels.Something.RequestModel) {
        worker = PostCommentReplayWorker()
        worker?.doSomeWork()
        
        let responseModel = PostCommentReplayModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
