excluded:
- Pods
- Carthage

line_length:
- 200 #warning
- 300 #error

identifier_name:
  min_length: 2 #only min_length

cyclomatic_complexity:
- 13

warning_threshold: 15

force_cast: warning

disabled_rules:
- trailing_whitespace
- vertical_whitespace
- nesting
- force_cast
- force_try
- notification_center_detachment
- multiple_closures_with_trailing_closure
- statement_position
- todo
- colon
