excluded:
- Pods
- Carthage

line_length:
- 350 #warning
- 400 #error

file_length:
- 1350 #warning
- 1950 #error

type_body_length:
- 405 #warning

identifier_name:
  min_length: 2 #only min_length

cyclomatic_complexity:
- 13

warning_threshold: 15

force_cast: warning

disabled_rules:
- trailing_whitespace
- vertical_whitespace
- nesting
- force_cast
- force_try
- notification_center_detachment
- multiple_closures_with_trailing_closure
- statement_position
- todo
- colon
- empty_enum_arguments
- function_body_length
- identifier_name
- implicit_getter
- opening_brace
- function_parameter_count

