//
//  PostShowRouter.swift
//  golos-ios
//
//  Created by msm72 on 31.07.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Input & Output protocols
@objc protocol PostShowRoutingLogic {
    func routeToUserProfileScene(byUserName name: String)
}

protocol PostShowDataPassing {
    var dataStore: PostShowDataStore? { get }
}

class PostShowRouter: NSObject, PostShowRoutingLogic, PostShowDataPassing {
    // MARK: - Properties
    weak var viewController: PostShowViewController?
    var dataStore: PostShowDataStore?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Routing
    func routeToUserProfileScene(byUserName name: String) {
        let storyboard          =   UIStoryboard(name: "UserProfileShow", bundle: nil)
        let destinationVC       =   storyboard.instantiateViewController(withIdentifier: "UserProfileShowVC") as! UserProfileShowViewController
        destinationVC.sceneMode =   .preview
        var destinationDS       =   destinationVC.router!.dataStore!

        passDataToUserProfileScene(userName: name, destination: &destinationDS)
        navigateToUserProfileScene(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: - Navigation
    func navigateToUserProfileScene(source: PostShowViewController, destination: UserProfileShowViewController) {
        source.show(destination, sender: nil)
    }
    
    
    // MARK: - Passing data
    func passDataToUserProfileScene(userName: String, destination: inout UserProfileShowDataStore) {
        destination.userName    =   userName
    }
}
