//
//  SettingsShowPresenter.swift
//  golos-ios
//
//  Created by msm72 on 24.07.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Presentation Logic protocols
protocol SettingsShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: SettingsShowModels.Items.ResponseModel)
}

class SettingsShowPresenter: SettingsShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: SettingsShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: SettingsShowModels.Items.ResponseModel) {
        let viewModel = SettingsShowModels.Items.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
