//
//  UserProfileShowPresenter.swift
//  golos-ios
//
//  Created by msm72 on 29.06.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Presentation Logic protocols
protocol UserProfileShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: UserProfileShowModels.Something.ResponseModel)
}

class UserProfileShowPresenter: UserProfileShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: UserProfileShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: UserProfileShowModels.Something.ResponseModel) {
        let viewModel = UserProfileShowModels.Something.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
