//
//  UserProfileShowRouter.swift
//  golos-ios
//
//  Created by msm72 on 29.06.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Input & Output protocols
@objc protocol UserProfileShowRoutingLogic {
    func routeToLoginShowScene()
}

protocol UserProfileShowDataPassing {
    var dataStore: UserProfileShowDataStore? { get }
}

class UserProfileShowRouter: NSObject, UserProfileShowRoutingLogic, UserProfileShowDataPassing {
    // MARK: - Properties
    weak var viewController: UserProfileShowViewController?
    var dataStore: UserProfileShowDataStore?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Routing
    func routeToLoginShowScene() {
        StateMachine.load().changeState(.loggedOut)
        User.current!.clearCache()
        User.current!.setIsAuthorized(false)
    }
}
