//
//  UserProfileShowRouter.swift
//  golos-ios
//
//  Created by msm72 on 29.06.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Input & Output protocols
@objc protocol UserProfileShowRoutingLogic {
    func routeToSettingsShowScene()
}

protocol UserProfileShowDataPassing {
    var dataStore: UserProfileShowDataStore? { get }
}

class UserProfileShowRouter: NSObject, UserProfileShowRoutingLogic, UserProfileShowDataPassing {
    // MARK: - Properties
    weak var viewController: UserProfileShowViewController?
    var dataStore: UserProfileShowDataStore?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Routing
    func routeToSettingsShowScene() {
        let storyboard      =   UIStoryboard(name: "SettingsShow", bundle: nil)
        let destinationVC   =   storyboard.instantiateViewController(withIdentifier: "SettingsShowVC") as! SettingsShowViewController

        navigateToSettingsShowScene(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: - Navigation
    func navigateToSettingsShowScene(source: UserProfileShowViewController, destination: SettingsShowViewController) {
        UIApplication.shared.statusBarStyle = .default
        
        source.show(destination, sender: nil)
        viewController?.showNavigationBar()
    }
}
