//
//  UserSubscribersShowPresenter.swift
//  golos-ios
//
//  Created by msm72 on 10/29/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Presentation Logic protocols
protocol UserSubscribersShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: UserSubscribersShowModels.Something.ResponseModel)
}

class UserSubscribersShowPresenter: UserSubscribersShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: UserSubscribersShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: UserSubscribersShowModels.Something.ResponseModel) {
        let viewModel = UserSubscribersShowModels.Something.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
