//
//  PostCommentInteractor.swift
//  golos-ios
//
//  Created by msm72 on 11.06.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Business Logic protocols
protocol PostCommentBusinessLogic {
    func doSomething(withRequestModel requestModel: PostCommentModels.Something.RequestModel)
}

protocol PostCommentDataStore {
//     var name: String { get set }
}

class PostCommentInteractor: PostCommentBusinessLogic, PostCommentDataStore {
    // MARK: - Properties
    var presenter: PostCommentPresentationLogic?
    var worker: PostCommentWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: PostCommentModels.Something.RequestModel) {
        worker = PostCommentWorker()
        worker?.doSomeWork()
        
        let responseModel = PostCommentModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
