//
//  UsersVoteShowPresenter.swift
//  golos-ios
//
//  Created by msm72 on 10/25/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Presentation Logic protocols
protocol UsersVoteShowPresentationLogic {
    func presentLoadUsersVoted(fromResponseModel responseModel: UsersVoteShowModels.Item.ResponseModel)
}

class UsersVoteShowPresenter: UsersVoteShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: UsersVoteShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentLoadUsersVoted(fromResponseModel responseModel: UsersVoteShowModels.Item.ResponseModel) {
        let viewModel = UsersVoteShowModels.Item.ViewModel(errorAPI: responseModel.errorAPI)
        viewController?.displayLoadUserVoted(fromViewModel: viewModel)
    }
}
