//
//  SettingsNotificationsShowModels.swift
//  golos-ios
//
//  Created by msm72 on 25.07.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Data models
enum SettingsNotificationsShowModels {
    // MARK: - Use cases
    enum Items {
        struct RequestModel {
        }
        
        struct ResponseModel {
        }
        
        struct ViewModel {
        }
    }
}
