//
//  ActiveKeyShowRouter.swift
//  golos-ios
//
//  Created by msm72 on 10.06.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Input & Output protocols
@objc protocol ActiveKeyShowRoutingLogic {
    func showLoginHelpShowScene()
}

class ActiveKeyShowRouter: NSObject, ActiveKeyShowRoutingLogic {
    // MARK: - Properties
    weak var viewController: ActiveKeyShowViewController?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Routing
    func showLoginHelpShowScene() {
        let logInHelpShowVC                     =   LogInHelpShowViewController.nibInstance()
        logInHelpShowVC.modalPresentationStyle  =   .overCurrentContext
        logInHelpShowVC.loginType               =   .activeKey
        
        viewController?.present(logInHelpShowVC, animated: true, completion: nil)
    }
}
