//
//  LogInShowPresenter.swift
//  golos-ios
//
//  Created by msm72 on 12.06.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Presentation Logic protocols
protocol LogInShowPresentationLogic {
    func presentAuthorizeUser(fromResponseModel responseModel: LogInShowModels.Something.ResponseModel)
}

class LogInShowPresenter: LogInShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: LogInShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentAuthorizeUser(fromResponseModel responseModel: LogInShowModels.Something.ResponseModel) {
        let viewModel = LogInShowModels.Something.ViewModel()
        viewController?.displayAuthorizeUser(fromViewModel: viewModel)
    }
}
