//
//  ActiveVotersShowPresenter.swift
//  golos-ios
//
//  Created by msm72 on 10/25/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Presentation Logic protocols
protocol ActiveVotersShowPresentationLogic {
    func presentSubscribe(fromResponseModel responseModel: ActiveVotersShowModels.Sub.ResponseModel)
    func presentLoadActiveVoters(fromResponseModel responseModel: ActiveVotersShowModels.Item.ResponseModel)
}

class ActiveVotersShowPresenter: ActiveVotersShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: ActiveVotersShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentSubscribe(fromResponseModel responseModel: ActiveVotersShowModels.Sub.ResponseModel) {
        let viewModel = ActiveVotersShowModels.Sub.ViewModel(isFollowing: responseModel.isFollowing, authorNickName: responseModel.authorNickName, errorAPI: responseModel.errorAPI)
        viewController?.displaySubscribe(fromViewModel: viewModel)
    }

    func presentLoadActiveVoters(fromResponseModel responseModel: ActiveVotersShowModels.Item.ResponseModel) {
        let viewModel = ActiveVotersShowModels.Item.ViewModel(errorAPI: responseModel.errorAPI)
        viewController?.displayLoadActiveVoters(fromViewModel: viewModel)
    }
}
