//
//  PostsShowModels.swift
//  golos-ios
//
//  Created by msm72 on 16.07.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Data models
enum PostsShowModels {
    // MARK: - Use cases
    enum Items {
        struct RequestModel {
            let postFeedType: PostsFeedType
        }
        
        struct ResponseModel {
            let error: ErrorAPI?
        }
        
        struct ViewModel {
            let error: ErrorAPI?
        }
    }
    
    enum ActiveVote {
        struct RequestModel {
            let isUpvote: Bool
        }
        
        struct ResponseModel {
            let isUpvote: Bool
            let errorAPI: ErrorAPI?
        }
        
        struct ViewModel {
            let isUpvote: Bool
            let errorAPI: ErrorAPI?
        }
    }
}
