//
//  PostsShowPresenter.swift
//  golos-ios
//
//  Created by msm72 on 16.07.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Presentation Logic protocols
protocol PostsShowPresentationLogic {
    func presentLoadPosts(fromResponseModel responseModel: PostsShowModels.Items.ResponseModel)
    func presentLikeVote(fromResponseModel responseModel: PostsShowModels.Like.ResponseModel)
}

class PostsShowPresenter: PostsShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: PostsShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentLoadPosts(fromResponseModel responseModel: PostsShowModels.Items.ResponseModel) {
        let loadPostsViewModel = PostsShowModels.Items.ViewModel(error: responseModel.error)
        viewController?.displayLoadPosts(fromViewModel: loadPostsViewModel)
    }
    
    func presentLikeVote(fromResponseModel responseModel: PostsShowModels.Like.ResponseModel) {
        let viewModel = PostsShowModels.Like.ViewModel(isLike: responseModel.isLike, isDislike: responseModel.isDislike, errorAPI: responseModel.errorAPI)
        viewController?.displayLikeVote(fromViewModel: viewModel)
    }
}
