//
//  RootShowPresenter.swift
//  golos-ios
//
//  Created by msm72 on 02.06.2018.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoloSwift

// MARK: - Presentation Logic protocols
protocol RootShowPresentationLogic {
//    func presentPosts(fromResponseModel responseModel: RootShowModels.Items.ResponseModel)
}

class RootShowPresenter: RootShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: RootShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
//    func presentPosts(fromResponseModel responseModel: RootShowModels.Items.ResponseModel) {
//        let viewModel = RootShowModels.Items.ViewModel(error: responseModel.error)
//        viewController?.displayPosts(fromViewModel: viewModel)
//    }
}
